### ISSUE TITLE
Exercise bike support

### ISSUE THREAD

**Issue by darren3** [zpukr/ArduRower#5]
Hi, do you have any plans to support exercise bikes or treadmills transmitting the FTMS standard?

**Comment by zpukr** [comment]
You must understand the context. I live in Ukraine, had to leave my house with a small sports bag 10 months ago, to this day cannot return there because the city is under Russian occupation. I haven't seen my rowing machine in all this time. Now I live in a small room where the electricity and the Internet are turned on for several hours a day. Therefore, I have neither the opportunity nor the desire to develop the project, all I can is minimal technical support and fix of existing bugs. At least until the victory of Ukraine, the situation will not change for the better, on the contrary, I can die every second, air raid sirens are howling right now. 21 century!

**Comment by darren3** [comment]
I'm really sorry for bothering you, I didn't understand your circumstances.
I wish you well, I am a pacifist and hate what is happening to you and your
people.

**Comment by zpukr** [comment]
> I'm really sorry for bothering you, I didn't understand your circumstances.
> I wish you well, I am a pacifist and hate what is happening to you and your
> people.

Today a "pacifist" sounds to me like "I don't care how many Ukrainians die." It's like for a victim of sexual assault during an attack, instead of real helping, you will begin to tell that you do not like sex. The time of the pacifists ended on February 24, 2022, today our army needs more weapons to destroy the invader and we were able to return to peaceful life. If the whole world is pacifists, like Switzerland for example, Ukrainians will simply be killed by Russia to the last man, one by one.
