### ISSUE TITLE
connection clarification question / lap measurements S4 water rower

### ISSUE THREAD

**Issue by john-2000** [zpukr/ArduRower#6]
First a very, very big thank you for this program! Secondly I am not sure if this is the right way to contact you and if I should have sent an email via the Garmin IQ store apologies. Hopefully the community can help me with my questions

My question relates to the distance measurement - I use the Garmin IQ app. 

To confirm to get the connection with the S4 on the water rower to the Garmin Watch - I think its should work by just starting the indoor rowing app with the ArduRower-IQ fields active. Do I need to do anything else? If the S4 is connected to my phone does this interfere with the connection to my Garmin Watch?

Do you know if it is possible to get autolaps working based on distance, it would be brilliant if an automatic lap were recorded in the Garmin history after every XXXm 

a very very big thank you for your work!

**Comment by zpukr** [comment]
_starting the indoor rowing app with the ArduRower-IQ fields active. Do I need to do anything else?_
nope
_If the S4 is connected to my phone does this interfere with the connection to my Garmin Watch?_
Bluetooth only supports one active connection, so you'll have to choose. As an option to solve the problem, you can also connect ArduRower on esp32 in parallel to the rotation sensor of the rowing machine, even without a screen, so that it works as a bluetooth server just for data transfer.
_autolaps working based on distance_
Garmin does not allow third-party applications to write to native fields like distance, so you will not be able to use the distance provided by ardurower-iq as an automatic lap, unfortunately. Use the time, I have no other options
